### ISSUE TITLE
@Types - TypeScript typings

### ISSUE THREAD

**Issue by JosefButzke** [PriceRunner/react-ga4#1]
ReactJS erro, need @types/react-ga4.

**Comment by codler** [comment]
Added TypeScript declarations https://github.com/PriceRunner/react-ga4/releases/tag/v1.0.1

**Comment by JonasRothmann** [comment]
Regarding this it seems gaOptions only lists one of the possible options, or am i wrong here?

**Comment by codler** [comment]
@JonasRothmann I updated the typings on gaOptions now. all contributions are welcome.
