### ISSUE TITLE
Debug Logging

### ISSUE THREAD

**Issue by aress31** [PriceRunner/react-ga4#12]
One of the most useful feature of `react-ga` is the debugging output to troubleshot issues as follows:

```
ReactGA.initialize(process.env.REACT_APP_GA_TRACKING_ID, {
  debug:
    !process.env.NODE_ENV ||
    process.env.NODE_ENV === 'development',
});
```

Could you please consider implementing this?

**Comment by codler** [comment]
I recommend using [Google Analytics Debugger Chrome Extension](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) for debugging

**Comment by aress31** [comment]
Could you not implement it out of the box like in `react-ga` this feature is a staple!
