### ISSUE TITLE
[Doc] Web Vitals Support/Integration

### ISSUE THREAD

**Issue by aress31** [PriceRunner/react-ga4#14]
Taken from the `Web Vitals` repository, here is the recommended way to send data to Google Analytics:

> #### Using `gtag.js` (Google Analytics 4)
> 
> [Google Analytics 4](https://support.google.com/analytics/answer/10089681) introduces a new Event model allowing custom parameters instead of a fixed category, action, and label. It also supports non-integer values, making it easier to measure Web Vitals metrics compared to previous versions.
> 
> ```js
> import {getCLS, getFID, getLCP} from 'web-vitals';
> 
> function sendToGoogleAnalytics({name, delta, value, id}) {
>   // Assumes the global `gtag()` function exists, see:
>   // https://developers.google.com/analytics/devguides/collection/ga4
>   gtag('event', name, {
>     // Built-in params:
>     value: delta, // Use `delta` so the value can be summed.
>     // Custom params:
>     metric_id: id, // Needed to aggregate events.
>     metric_value: value, // Optional.
>     metric_delta: delta, // Optional.
> 
>     // OPTIONAL: any additional params or debug info here.
>     // See: https://web.dev/debug-web-vitals-in-the-field/
>     // metric_rating: 'good' | 'ni' | 'poor',
>     // debug_info: '...',
>     // ...
>   });
> }
> 
> getCLS(sendToGoogleAnalytics);
> getFID(sendToGoogleAnalytics);
> getLCP(sendToGoogleAnalytics);
> ```

However the `ReactGA.event` function does not seem to implement all these fields, could you please look into this and advise on it as sending performances data is really important.

For more information: https://github.com/GoogleChrome/web-vitals/blob/main/README.md

Alternatively, if you could provide an example on how to set up the custom dimension and set up the sending of the analytics and add it to the doc, big kudos!

**Comment by codler** [comment]
Great issue report. 

Here is an example how you can use with react-ga4
```js
import ReactGA from 'react-ga4';
import {getCLS, getFID, getLCP} from 'web-vitals';

function sendToGoogleAnalytics({name, delta, value, id}) {
  ReactGA.send({
    hitType: 'event',
    eventCategory: 'Web Vitals',
    eventAction: name,
    eventLabel: id,
    nonInteraction: true,
    // Built-in params:
    value: Math.round(name === 'CLS' ? delta * 1000 : delta), // Use `delta` so the value can be summed.
    // Custom params:
    metric_id: id, // Needed to aggregate events.
    metric_value: value, // Optional.
    metric_delta: delta, // Optional.

    // OPTIONAL: any additional params or debug info here.
    // See: https://web.dev/debug-web-vitals-in-the-field/
    // metric_rating: 'good' | 'ni' | 'poor',
    // debug_info: '...',
    // ...
  });
}

getCLS(sendToGoogleAnalytics);
getFID(sendToGoogleAnalytics);
getLCP(sendToGoogleAnalytics);

**Comment by aress31** [comment]
The custom params like metric_id, etc. Need to be set as dimension metric I reckon? Did you manage to send all these information as they are used to aggregate  user data and avoid duplicate entries.

**Comment by aress31** [comment]
Any update on that? With my current implementation (as above) I get tons of event sent to my dashboard instead of one aggregated one per page due to the limitations I described in previous post. Could you kindly put this ticket on the list of priorities? 🙏

**Comment by codler** [comment]
The result of the above example would send this gtag information
```js
sendToGoogleAnalytics({
  name: "CLS",
  delta: 12.34,
  value: 1,
  id: "v2-1632380328370-6426221164013",
});
/*
gtag("event", "CLS", {
  "event_category": "Web Vitals", 
  "event_label": "v2-1632380328370-6426221164013", 
  "metric_delta": 12.34, 
  "metric_id": "v2-1632380328370-6426221164013", 
  "metric_value": 1, 
  "non_interaction": true, 
  "value": 12340,
})
*/
```

As web-vitals docs recommend. 
I do not know about metrics or aggregation part other than what web-vitals recommended.

**Comment by codler** [comment]
Looks like it should work, it looks same as https://github.com/GoogleChrome/web-vitals/issues/168
