### ISSUE TITLE
[Doc] OutboundLink

### ISSUE THREAD

**Issue by aress31** [PriceRunner/react-ga4#15]
`OutboundLink` is marked as deprecated and I am not sure what method to use instead and how to do. Would you please mind adding in the doc how/what to do? :)

```js
The signature '({ label }: { label: string; }, hitCallback: Function): void' of 'ReactGA.outboundLink' is deprecated.ts(6387)
ga4.d.ts(87, 8): The declaration was marked as deprecated here.
(method) GA4.outboundLink({ label }: {
    label: string;
}, hitCallback: Function): void
@since — v1.0.6
@param options
@param hitCallback
@deprecated
```

**Comment by codler** [comment]
I recommend to use `enhanced measurement` feature in Google Analytics. https://support.google.com/analytics/answer/9216061
