### ISSUE TITLE
Custom event parameters

### ISSUE THREAD

**Issue by ryancrunchi** [PriceRunner/react-ga4#16]
Since ga4, events can be sent with custom parameters.
The current implementation of ReactGA does not match gtag.
- Event action is a separate parameter
- All predefined event parameters (category, label, value, nonInteraction, transport) are not needed. Instead we can send any parameters we need.

Something like this would match gtag :
`ReactGA.event('myEvent', { my_param_1: 'my_value_1' })`

https://developers.google.com/tag-platform/gtagjs/reference#event

**Comment by codler** [comment]
Thanks for reporting. It is now possible to send custom events with custom parameters from [v1.1.0](https://github.com/PriceRunner/react-ga4/releases/tag/v1.1.0)
```js
ReactGA.event("screen_view", {
  app_name: "myAppName",
  screen_name: "Home",
});

**Comment by Definence** [comment]
@codler please put passing parameters into source documentation
