### ISSUE TITLE
Equivalent to gtag set

### ISSUE THREAD

**Issue by pedrommuller** [PriceRunner/react-ga4#18]
how can I set a property like this?

gtag('set', 'user_properties', { 'user_Id' : '12345' });

something like this:
 ReactGA.set( {
          'user_properties': { 'user_Id' : '12345' }
        } );

**Comment by codler** [comment]
From version 1.2.0 you can do
```
ReactGA.gtag('set', 'user_properties', { 'user_Id' : '12345' });
