### ISSUE TITLE
No event category or label values

### ISSUE THREAD

**Issue by babipal** [PriceRunner/react-ga4#20]
I'm setting event category and label values for each of my events, but cannot see any data in my GA4. In every report, it says `(not set)` - any ideas?

**Comment by codler** [comment]
What does your code look like?

**Comment by babipal** [comment]
Sorry for the delay. I wanted to verify the data before proceeding. It looks like the data is there - I connected my GA4 property to a BigQuery instance, and can see `event_category` and `event_label` having values. So, I then created custom dimensions in the GA4 property for `event_category` and `event_label`, and after a while, could see the data. I'm new to GA4, it seems odd that category and label are not available as dimensions by default.
