### ISSUE TITLE
Why create 200 dimensions & metrics with arbitrary values in custom_map?

### ISSUE THREAD

**Issue by Loque-** [PriceRunner/react-ga4#21]
Hi there, I am implementing this library but am curious why these lines exists: https://github.com/PriceRunner/react-ga4/blob/0e2e3a624d8c8394438e5ea955f6dabdf01304e4/src/ga4.js#L473-L488

It creates 10.5kb of JSON that is then sent, and yea, not sure why, or how to stop it from doing so.

Many thanks.

**Comment by codler** [comment]
It is to be backward compatible with how you used before with `analytics.js`(now are `gtag.js`). But yeah this can be optimised for new users who dosen't use the old way of custom dimensions or custom metrics.

Ref.
https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets
https://developers.google.com/analytics/devguides/collection/gtagjs/custom-dims-mets

**Comment by Loque-** [comment]
Thank you for getting back to me.

I understand custom metrics and dimensions (that you might want to define them and send them), but I don't understand why you would want to create 200 dimensions and metrics that just have their own name as their value regardless of whether the implementation defines a custom_map or not.

It would be awesome, that if an entry is defined, it passes that on, but if not, that it doesn't add these 200 entries - at least in my use case.

![Screenshot 2021-11-01 at 16 12 43](https://user-images.githubusercontent.com/657572/139703909-8d7a3bf9-d5b5-4f99-a9d8-986a715546cb.png)

hope this ticket helps - appreciate the lib.

**Comment by codler** [comment]
> I understand custom metrics and dimensions (that you might want to define them and send them), but I don't understand why you would want to create 200 dimensions and metrics that just have their own name as their value regardless of whether the implementation defines a custom_map or not.

It is because the library doesn't know what dimensions/metrics are used until the consumer send an event. and custom_map can only be set during initialisation so thats why they are pre set.

From version 1.4.0
I added an option now `legacyDimensionMetric` where you can switch off these extra mapping in custom_map.
```js
ReactGA.initialize("your GA measurement id", { legacyDimensionMetric : false });
```

alternative you can now also override or extend part of react-ga4 implementation 

```js
import { ReactGAImplementation } from "react-ga4";

class MyCustomOverriddenClass extends ReactGAImplementation {}

export default new MyCustomOverriddenClass();
```
