### ISSUE TITLE
ReactGA.event sends event title with first letter captitalised

### ISSUE THREAD

**Issue by sakshambhatt** [PriceRunner/react-ga4#22]
[ReactGA initialize](https://github.com/react-ga/react-ga#reactgainitializegatrackingid-options), gives options to make the titleCase boolean false. Could such an option be added in react-ga4 as well? 
![image](https://user-images.githubusercontent.com/33225002/139799815-01ae3996-8c01-4844-88a1-9ece091b79d7.png)

So that following code, leads to `add_to_cart` and not in `Add_to_cart`?
```
ReactGA.initialize( process.env.GA_MEASUREMENT_ID, { gaOptions: { titleCase: false } } );
ReactGA.event({
      category: "shopping",
      action: "add_to_cart",
      label: "name",
});
````

**Comment by codler** [comment]
You can use the following code for `add_to_cart`.
```js
ReactGA.event("add_to_cart", {
  items: [{ item_name: "name" }],
});
```
https://developers.google.com/tag-platform/gtagjs/reference/events#add_to_cart

**Comment by sakshambhatt** [comment]
Thank you for the above comment. The above link has many relevant events, and that certainly helps. But what if I were to create a custom event like for example, `price_compared` or `view_certificate`? It becomes increasingly difficult with custom events if there is existing data as I will have both `Price_compared` and `price_compared`.

**Comment by codler** [comment]
I don't understand what you meant. If you use `ReactGA.event(name, params)` method signature you won't have `titleCase`.

**Comment by quyctd** [comment]
@sakshambhatt, I have the same issue. Maybe the suggestion of Codler is not clear. You can do like this:
```
ReactGA.event("add_to_cart", {
      event_category: "shopping",
      event_label: "name",
});
```

It'll result in no `titleCase` as you expected.

**Comment by sakshambhatt** [comment]
Thank you @quyctd , I tried this and it works. @codler ,  it would be really appreciated if a sample were added to README like the one suggested by @quyctd in above comment. In fact, I will raise a PR myself.

**Comment by djakaitis** [comment]
I think the bigger issue here is presumptively adding title case. Shouldn't user input be kept as is?
