### ISSUE TITLE
gtagOptions doesn't work

### ISSUE THREAD

**Issue by Kevin-Hamilton** [PriceRunner/react-ga4#24]
The example in the readme shows: 
```
ReactGA.initialize([
  {
    trackingId: "your GA measurement id",
    gaOptions: {...}, // optional
    gtagOptions: {...}, // optional
  },
  {
    trackingId: "your second GA measurement id",
  },
]);
```

But it appears to me that setting gtagOptions here does not work.  I think it is a bug on this line:
https://github.com/PriceRunner/react-ga4/blob/6822d0f02b85a9dc2abc79793a358805485b7f60/src/ga4.js#L193
Should that be config.gtagOptions ...?

**Comment by codler** [comment]
Thanks for reporting! It is now fixed in 1.4.1
