### ISSUE TITLE
Send pageview with a custom path

### ISSUE THREAD

**Issue by azielstyle** [PriceRunner/react-ga4#25]
hI

I'm trying this function  and  simple not working =(
`
ReactGA.send({ hitType: "pageview", page: "/my-path" });`

debugging the issue i just found out that parameters are not passed correctly

![imagen](https://user-images.githubusercontent.com/2739956/141702602-a48fcc50-4d0e-4ea3-9eda-4de1296dcd65.png)

or it is just me?

this is my code 
```

import ReactGA from 'react-ga4';
import { GOOGLE_ANALYTICS_GA4_ID } from '../api/urlConfig';

export const initGA = () => {
   ReactGA.initialize(
       GOOGLE_ANALYTICS_GA4_ID,
       { debug: true }
       );
}

export const logPageView = () => {
    ReactGA.set({
        page: window.location.pathname
        
    });

    ReactGA.send("pageview");
    // ReactGA.pageview(window.location.pathname);
};

export const logPageEventCustom = (pageEvent, page) =>{

    ReactGA.send({ hitType: "pageview", page: "/my-path" });
   
};

```

i'm using logPageEventCustom  function but the custom route  "/my-path" is not appearing

and this is the console log
![imagen](https://user-images.githubusercontent.com/2739956/141705965-62f60fa6-3435-4d3e-90ff-2914014dd59f.png)

please help

thanks

**Comment by azielstyle** [comment]
i had an older version, sorry!

**Comment by codler** [comment]
Duplicate #9
