### ISSUE TITLE
gtag script added at end of `body` instead of adding it in `head`

### ISSUE THREAD

**Issue by AlbertoSadoc** [PriceRunner/react-ga4#29]
The gtag script is being inserted at the end of the `body` section but Google instructs to add the gtag script in the `head` section of the HTML:
![image](https://user-images.githubusercontent.com/6703955/149953538-34e37411-84b2-4001-81bd-80307e0f9862.png)

**Comment by NaincyKumariKnoldus** [comment]
Hey @AlbertoSadoc Can I do this please?
but I have checked I havent found any script tag here.

**Comment by AlbertoSadoc** [comment]
I'm not sure what you mean by 
>  havent found any script tag here.

but looking at this part of the code

https://github.com/PriceRunner/react-ga4/blob/f31ed502adec6dc9dd68e3b59d39c1857880f433/src/ga4.js#L93-L95

the script is appended to the `body` element, but Google instructs in to insert that script in the `head` section.

**Comment by NaincyKumariKnoldus** [comment]
okay @AlbertoSadoc Can I do this?

**Comment by NaincyKumariKnoldus** [comment]
okay @AlbertoSadoc I will do this.
