### ISSUE TITLE
testMode does not print anything in the console.log

### ISSUE THREAD

**Issue by nigellima** [PriceRunner/react-ga4#3]
Hi, thanks for the work on migrating the react-ga to GA4

I'm trying to use this one, but cant get it to work or print anything in the console:

This is my custom hook:

```

const TRACKING_ID = 'G-XXXXXXX';

browserHistory.listen((location) => {
  ReactGA.set({ page: location.pathname });
  ReactGA.pageview(location.pathname);
});

export const useGA = () => {
  const { authStore } = useStores();
  const { isAuthenticated, user } = authStore;

  useEffect(() => {
    if (isAuthenticated) {
      console.log('initializing');
      ReactGA.initialize(TRACKING_ID, {
        testMode: true,
        gaOptions: {
          userId: String(user?.id),
        },
      });
    }
  }, [isAuthenticated]);
};
```

I set testMode to true in order to have the logs (like the react-ga debug flag). Also, I'm using the G-XXX type of tracking id but I cant see anything updating in the GA dashboard. Am I missing something?

**Comment by codler** [comment]
You can use [Google Analytics Debugger Chrome Extension](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) to see logs. `testMode` are only to prevent sending to Analytics
