### ISSUE TITLE
Custom user id and documentation

### ISSUE THREAD

**Issue by handofthecode** [PriceRunner/react-ga4#4]
Is it possible to set a custom user id?

It would be great to have a little more information in the Readme.

Thanks!

**Comment by handofthecode** [comment]
In the original react-ga you could set userId in gaOptions ```
gaOptions: {
    userId: 123
  }
```
but it looks like in this library `cookieUpdate` is the only value that can be set in `gaOptions`.

**Comment by handofthecode** [comment]
In the original react-ga you could set userId in gaOptions 
```
gaOptions: {
userId: 123
}
```
but it looks like in this library `cookieUpdate` is the only value that can be set in `gaOptions`.

**Comment by codler** [comment]
The latest version 1.0.3 have updated the typings with gaOptions.

**Comment by handofthecode** [comment]
Awesome. Thanks!
