### ISSUE TITLE
Not possible to anonymizeIp and location anymore with react-ga4.

### ISSUE THREAD

**Issue by indhumathi1985** [PriceRunner/react-ga4#52]
Not possible to anonymizeIp and location anymore with react-ga4.

ReactGA.set({ anonymizeIp: true })
ReactGA.set({ location: 'Anonymized' })

Doesn't really work with anonymizing

**Comment by codler** [comment]
> In Google Analytics 4, IP anonymization is not necessary since IP addresses are not logged or stored.

https://support.google.com/analytics/answer/9019185#IP&zippy=%2Cin-this-article
