### ISSUE TITLE
Delay of 4 to 5 seconds for pageview event to fire

### ISSUE THREAD

**Issue by simranbentel** [PriceRunner/react-ga4#8]
When a new pageview event is executed in the code, it takes almost 5 seconds for the actual network call to occur.

**Comment by codler** [comment]
Can you show on https://codesandbox.io/

**Comment by simranbentel** [comment]
https://codesandbox.io/s/vibrant-sound-z12je?file=/src/Page1.js:0-74

Tried to setup and reproduce, I am not even seeing the `collect` network calls when I navigate from page to page. Just your sandbox tracking. The usage mirrors my own project where the send function is called in useEffect hook.

**Comment by codler** [comment]
I see no delays when I debug with [Google Analytics Debugger Chrome Extension](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en)

Google Analytics have different ways of sending data, not always using collect. https://developers.google.com/analytics/devguides/collection/analyticsjs/sending-hits#specifying_different_transport_mechanisms
Also make sure you have disabled any adblocker. https://github.com/react-ga/react-ga/issues/101
