### ISSUE TITLE
sending pageview with custom path

### ISSUE THREAD

**Issue by samuelcolvin** [PriceRunner/react-ga4#9]
Thanks for the package, got me out of a tight spot.

The `.pageview()` method is deprecated, but `.send('pageview')` doesn't obviously allow me to include a custom path.

Help Appreciated.

**Comment by codler** [comment]
I updated the package now from `v1.0.5` to support sending pageview with path, title and location through send method. https://github.com/PriceRunner/react-ga4/blob/v1.0.5/src/ga4.test.js#L307-L346

```js
ReactGA.send({ hitType: "pageview", page: "/my-path" });
